[package]
name = "mariochao/beloved-remote"
description = "Experimental manager for (unreliable) remote events and remote functions."

version = "0.0.1"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/MarioChao/beloved-remote"

[dependencies]
